version: "3"

services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_DB: zoo
      POSTGRES_USER: otus
      POSTGRES_PASSWORD: otus123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

