# Generated by Django 5.0.6 on 2024-07-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildanimal',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
