# Generated by Django 5.0.6 on 2024-07-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_animalcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildanimal',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
